name: Deploy-Stack-2025
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Docker --wait
        run: docker compose up -d --build

      - name: Fix Permissions
        run: docker exec doker-php-php-app-1 chown -R www-data:www-data /var/www/html

      - name: Test Connection
        run: |
          sleep 15
          curl -s http://localhost:8080 | grep "Connected successfully"

